# Generated by Django 5.2.8 on 2025-11-11 03:44

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text="Usado para las URLs. Ej: 'deportes'", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text="Usado para las URLs. Ej: 'inteligencia-artificial'", unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(help_text="URL amigable, autogenerada o manual. Ej: 'mi-gran-noticia-2025'", max_length=255, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('banner', models.ImageField(help_text='Imagen principal que aparecerá en la parte superior de la noticia.', upload_to='noticias/banners/%Y/%m/%d/', verbose_name='Banner Principal')),
                ('vistas', models.PositiveIntegerField(default=0, help_text='Contador de vistas', verbose_name='Vistas')),
                ('tiempo_lectura', models.PositiveSmallIntegerField(default=5, help_text='Tiempo estimado de lectura en minutos', verbose_name='Tiempo de lectura (min)')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('publicado', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_escritas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.categoria', verbose_name='Categoría')),
                ('tags', models.ManyToManyField(blank=True, related_name='noticias', to='noticias.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
