# Generated by Django 5.2.8 on 2025-11-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(default='https://placehold.co/616x256?text=Categoría', help_text='Imagen principal de la categoría.', upload_to='categorias/%Y/%m/%d/', verbose_name='Banner Principal'),
        ),
    ]
