# Generated by Django 5.2.8 on 2025-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='banner',
            field=models.ImageField(default='https://placehold.co/600x400.webp', help_text='Imagen principal de la categoría.', upload_to='categorias/%Y/%m/%d/', verbose_name='Banner Principal'),
        ),
    ]
