# Generated by Django 5.2.8 on 2025-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_categoria_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='banner_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='noticias/banners/%Y/%m/%d/', verbose_name='Thumbnail Mediano'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='banner_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='noticias/banners/%Y/%m/%d/', verbose_name='Thumbnail Pequeño'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='banner',
            field=models.ImageField(help_text='Imagen principal. Se redimensionará a 1920x1080 si es más grande.', upload_to='noticias/banners/%Y/%m/%d/', verbose_name='Banner Principal'),
        ),
    ]
