# Generated by Django 5.2.8 on 2025-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_banner_medium_noticia_banner_small_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('icono', models.CharField(help_text="Clase CSS del icono (ej: 'fab fa-facebook')", max_length=100, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['nombre'],
            },
        ),
    ]
