# Generated by Django 5.2.8 on 2025-11-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_redsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redsocial',
            name='icono',
        ),
        migrations.AddField(
            model_name='redsocial',
            name='svg_icono',
            field=models.CharField(default='facebook', help_text="Clase CSS del icono (ej: 'fab fa-facebook')", max_length=100, verbose_name='Icono'),
        ),
    ]
