# Generated by Django 5.2.8 on 2025-11-15 16:15

from django.db import migrations

redes_a_crear = [
        {
            'nombre': 'Facebook', # El nombre de la red
            'url': 'https://www.facebook.com/tu_usuario',
            'svg_icono': 'facebook' # Su ícono específico
        },
        {
            'nombre': 'Instagram',
            'url': 'https://www.instagram.com/tu_usuario',
            'svg_icono': 'instagram'
        },
        {
            'nombre': 'Teléfono',
            'url': 'https://www.twitter.com/tu_usuario',
            'svg_icono': 'twitter-x'
        },
        {
            'nombre': 'Soporte (Email)', # Un ejemplo que no es 'facebook'
            'url': 'mailto:soporte@tuempresa.com',
            'svg_icono': 'correo'
        },
        
    ]

def crear_redes_iniciales(apps, schema_editor):
    """
    Poblamos la tabla RedSocial con datos iniciales.
    """
    # Obtenemos el modelo 'RedSocial' de la app 'noticias'
    RedSocial = apps.get_model('noticias', 'RedSocial')
    
    # Lista de redes que queremos crear
    
    
    # Usamos .get_or_create() para no crear duplicados si
    # la migración se corre accidentalmente de nuevo.
    for red_data in redes_a_crear:
        # Usamos 'nombre' como identificador único
        RedSocial.objects.get_or_create(
            nombre=red_data['nombre'],
            defaults=red_data
        )

def revertir_creacion(apps, schema_editor):
    """
    Si deshacemos la migración, borramos estas redes.
    """
    RedSocial = apps.get_model('noticias', 'RedSocial')
    nombres = [red['nombre'] for red in redes_a_crear]
    RedSocial.objects.filter(nombre__in=nombres).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_remove_redsocial_icono_redsocial_svg_icono'),
    ]

    operations = [
        migrations.RunPython(crear_redes_iniciales, reverse_code=revertir_creacion),
    ]
